language: ruby

cache: bundler

sudo: false

rvm:
  - 2.4.1

matrix:
  include:
    test_isolated

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile-1.9
    - rvm: 2.2
      script: bundle exec rake test_isolated
